{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kivo-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kivo.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-redirect-to-https@kubernetescrd" .Values.namespace | quote }}
    {{- else }}
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if .Values.ingress.tls.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManager.clusterIssuer | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- if .Values.ingress.tls.hosts }}
        {{- toYaml .Values.ingress.tls.hosts | nindent 8 }}
        {{- else }}
        - {{ .Values.ingress.host }}
        - www.{{ .Values.ingress.host }}
        - kivo.{{ .Values.ingress.host }}
        - auth.{{ .Values.ingress.host }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.tls.hosts }}
    {{- range .Values.ingress.tls.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kivo-web
                port:
                  name: http
    {{- end }}
    {{- else }}
    # Admin/Marketing Portal
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kivo-web
                port:
                  name: http
    - host: www.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kivo-web
                port:
                  name: http
    # Auth Portal
    - host: auth.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kivo-web
                port:
                  name: http
    {{- end }}
{{- end }}
