{{- if .Values.reflector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kivo.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "kivo-staging/ghcr-pull-secret"
type: kubernetes.io/dockerconfigjson
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: kivo-api-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kivo.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "kivo-staging/kivo-api-secret"
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: kivo-db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kivo.labels" . | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "kivo-staging/kivo-db-credentials"
type: Opaque
data: {}
{{- end }}
